"""
Comprehensive Indian Government Schemes Registry.
Covers national and state-specific schemes across all categories.
"""

# All Indian States and Union Territories (28 states + 8 UTs)
INDIAN_STATES = [
    # States
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    # Union Territories
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
]

# Occupation options for eligibility matching
OCCUPATIONS = [
    "farmer",
    "agricultural_laborer",
    "laborer",
    "construction_worker",
    "street_vendor",
    "domestic_worker",
    "self_employed",
    "small_business",
    "artisan",
    "student",
    "homemaker",
    "retired",
    "unemployed",
    "others",
]

SCHEMES = [
    # ========== AGRICULTURE & FARMER SCHEMES ==========
    {
        "id": "PMKISAN",
        "name": "PM-KISAN Samman Nidhi",
        "description": "Direct income support of ₹6,000 per year to farmer families in three equal installments.",
        "official_link": "https://pmkisan.gov.in/",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "criteria": {
            "farmer": True,
            "income_max": 200000,
        },
        "documents": ["Aadhaar Card", "Bank Account Details", "Land Ownership Papers"],
    },
    {
        "id": "PMFBY",
        "name": "Pradhan Mantri Fasal Bima Yojana",
        "description": "Crop insurance scheme for farmers against natural calamities, pests and diseases.",
        "official_link": "https://pmfby.gov.in/",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "criteria": {"farmer": True},
        "documents": ["Aadhaar Card", "Bank Account", "Land Records", "Crop Details"],
    },
    {
        "id": "KALIA",
        "name": "KALIA Scheme (Odisha)",
        "description": "Krushak Assistance for Livelihood and Income Augmentation – financial support for farmers in Odisha.",
        "official_link": "https://kalia.odisha.gov.in/",
        "ministry": "Government of Odisha",
        "criteria": {
            "farmer": True,
            "state": "Odisha",
        },
        "documents": ["Aadhaar Card", "Bank Account", "Land Records"],
    },
    # ========== HEALTH SCHEMES ==========
    {
        "id": "PMJAY",
        "name": "Ayushman Bharat PM-JAY",
        "description": "Health insurance cover of ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
        "official_link": "https://pmjay.gov.in/",
        "ministry": "Ministry of Health & Family Welfare",
        "criteria": {"income_max": 250000},
        "documents": ["Ration Card", "Aadhaar Card", "Income Certificate"],
    },
    {
        "id": "JANAUSHADHI",
        "name": "PM Bhartiya Jan Aushadhi Pariyojana",
        "description": "Affordable quality medicines through Jan Aushadhi Kendras at 50-90% lower cost.",
        "official_link": "https://janaushadhi.gov.in/",
        "ministry": "Ministry of Chemicals & Fertilizers",
        "criteria": {},
        "documents": ["Any valid ID", "Prescription from doctor"],
    },
    # ========== WOMEN & CHILD SCHEMES ==========
    {
        "id": "PMUY",
        "name": "Pradhan Mantri Ujjwala Yojana",
        "description": "Free LPG connections to women from BPL families.",
        "official_link": "https://www.pmuy.gov.in/",
        "ministry": "Ministry of Petroleum & Natural Gas",
        "criteria": {
            "gender": "Female",
            "income_max": 120000,
            "age_min": 18,
        },
        "documents": ["BPL Card", "Aadhaar Card", "Bank Account", "Passport Photo"],
    },
    {
        "id": "SUKANYA",
        "name": "Sukanya Samriddhi Yojana",
        "description": "Savings scheme for girl child with 8.2% interest and tax benefits under 80C.",
        "official_link": "https://www.nsiindia.gov.in/",
        "ministry": "Ministry of Finance",
        "criteria": {
            "gender": "Female",
            "age_max": 10,
        },
        "documents": ["Birth Certificate of Girl", "Parent's ID Proof", "Address Proof"],
    },
    {
        "id": "DAYNRLM",
        "name": "Deendayal Antyodaya Yojana - NRLM",
        "description": "Empowers rural poor women through Self Help Groups for sustainable livelihoods.",
        "official_link": "https://aajeevika.gov.in/",
        "ministry": "Ministry of Rural Development",
        "criteria": {
            "gender": "Female",
            "income_max": 150000,
            "age_min": 18,
        },
        "documents": ["Aadhaar Card", "BPL Card", "Bank Account"],
    },
    {
        "id": "ORUNODOI",
        "name": "Orunodoi 3.0 (Assam)",
        "description": "Monthly financial assistance of ₹1,250 to women-headed families in Assam.",
        "official_link": "https://finance.assam.gov.in/portlets/orunodoi-30",
        "ministry": "Government of Assam",
        "criteria": {
            "gender": "Female",
            "income_max": 200000,
            "age_min": 18,
            "state": "Assam",
        },
        "documents": ["Aadhaar Card", "Bank Account", "Residence Proof"],
    },
    {
        "id": "LADLI_BEHNA",
        "name": "Ladli Behna Yojana (Madhya Pradesh)",
        "description": "Monthly financial assistance of ₹1,250 to women in Madhya Pradesh.",
        "official_link": "https://mp.gov.in/",
        "ministry": "Government of Madhya Pradesh",
        "criteria": {
            "gender": "Female",
            "age_min": 21,
            "state": "Madhya Pradesh",
        },
        "documents": ["Aadhaar Card", "Bank Account", "Residence Proof"],
    },
    {
        "id": "KANYASHREE",
        "name": "Kanyashree Prakalpa (West Bengal)",
        "description": "Cash transfer scheme for girl students to prevent child marriage and encourage education.",
        "official_link": "https://www.wbkanyashree.gov.in/",
        "ministry": "Government of West Bengal",
        "criteria": {
            "gender": "Female",
            "age_min": 13,
            "age_max": 18,
            "state": "West Bengal",
        },
        "documents": ["Birth Certificate", "School Certificate", "Bank Account", "Aadhaar"],
    },
    # ========== HOUSING SCHEMES ==========
    {
        "id": "PMAY",
        "name": "Pradhan Mantri Awas Yojana",
        "description": "Affordable housing with interest subsidy up to ₹2.67 lakh on home loans.",
        "official_link": "https://pmaymis.gov.in/",
        "ministry": "Ministry of Housing & Urban Affairs",
        "criteria": {
            "income_max": 300000,
            "age_min": 21,
            "age_max": 70,
        },
        "documents": ["Income Proof", "Aadhaar Card", "Property Documents", "Bank Statements"],
    },
    {
        "id": "PMAY_G",
        "name": "Pradhan Mantri Awas Yojana - Gramin",
        "description": "Housing for rural poor with financial assistance for construction.",
        "official_link": "https://pmayg.nic.in/",
        "ministry": "Ministry of Rural Development",
        "criteria": {"income_max": 120000},
        "documents": ["Aadhaar", "Land Records", "Income Certificate", "Bank Account"],
    },
    # ========== PENSION & SOCIAL SECURITY ==========
    {
        "id": "NSAP",
        "name": "National Social Assistance Programme",
        "description": "Monthly pension for elderly (60+), widows, and disabled from BPL families.",
        "official_link": "https://nsap.nic.in/",
        "ministry": "Ministry of Rural Development",
        "criteria": {
            "age_min": 60,
            "income_max": 100000,
        },
        "documents": ["Age Proof", "BPL Card", "Bank Account", "Disability Certificate (if applicable)"],
    },
    {
        "id": "PMSYM",
        "name": "PM Shram Yogi Maan-dhan",
        "description": "Pension scheme for unorganized workers – ₹3,000 monthly after 60 years.",
        "official_link": "https://maandhan.in/",
        "ministry": "Ministry of Labour & Employment",
        "criteria": {
            "age_min": 18,
            "age_max": 40,
            "income_max": 180000,
            "occupations": ["laborer", "construction_worker", "street_vendor", "domestic_worker", "others"],
        },
        "documents": ["Aadhaar Card", "Bank Account", "Mobile Number"],
    },
    {
        "id": "APY",
        "name": "Atal Pension Yojana",
        "description": "Pension scheme for workers in unorganized sector – guaranteed pension ₹1,000–5,000/month.",
        "official_link": "https://www.npscra.nsdl.co.in/",
        "ministry": "Ministry of Finance",
        "criteria": {
            "age_min": 18,
            "age_max": 40,
        },
        "documents": ["Aadhaar Card", "Bank Account", "Mobile Number"],
    },
    # ========== MSME & BUSINESS SCHEMES ==========
    {
        "id": "MUDRA",
        "name": "Pradhan Mantri MUDRA Yojana",
        "description": "Loans up to ₹10 lakh for non-corporate small business – Shishu, Kishore, Tarun categories.",
        "official_link": "https://www.mudra.org.in/",
        "ministry": "Ministry of Finance",
        "criteria": {
            "age_min": 18,
            "occupations": ["self_employed", "small_business", "artisan", "others"],
        },
        "documents": ["Business Plan", "Identity Proof", "Address Proof"],
    },
    {
        "id": "UDYAM",
        "name": "Udyam Registration",
        "description": "Free, paperless MSME registration for access to subsidies and government benefits.",
        "official_link": "https://udyamregistration.gov.in/",
        "ministry": "Ministry of MSME",
        "criteria": {
            "age_min": 18,
            "business_owner": True,
        },
        "documents": ["Aadhaar Card", "PAN Card", "Business Details"],
    },
    {
        "id": "STANDUP",
        "name": "Stand-Up India",
        "description": "Bank loans ₹10 lakh to ₹1 crore for SC/ST or women entrepreneurs.",
        "official_link": "https://www.standupmitra.in/",
        "ministry": "Ministry of Finance",
        "criteria": {
            "age_min": 18,
            "business_owner": True,
            "categories_or_female": ["SC", "ST"],
        },
        "documents": ["Aadhaar", "Caste Certificate (if SC/ST)", "Business Plan", "Bank Account"],
    },
    # ========== RURAL EMPLOYMENT ==========
    {
        "id": "MGNREGA",
        "name": "MGNREGA",
        "description": "100 days of guaranteed wage employment per year for rural households.",
        "official_link": "https://nrega.nic.in/",
        "ministry": "Ministry of Rural Development",
        "criteria": {
            "age_min": 18,
            "occupations": ["laborer", "agricultural_laborer", "unemployed", "others"],
        },
        "documents": ["Job Card", "Aadhaar Card", "Bank Account"],
    },
    # ========== SC/ST/OBC SCHEMES ==========
    {
        "id": "E_UTTHAAN",
        "name": "e-Utthaan (SC Development Program)",
        "description": "Development Action Plan for Scheduled Castes – education and livelihood support.",
        "official_link": "https://e-utthaan.gov.in/",
        "ministry": "Ministry of Social Justice & Empowerment",
        "criteria": {
            "category": "SC",
            "income_max": 300000,
        },
        "documents": ["Caste Certificate", "Aadhaar Card", "Income Certificate"],
    },
    {
        "id": "SCST_HUB",
        "name": "National SC-ST Hub",
        "description": "Support for SC/ST entrepreneurs in public procurement and business development.",
        "official_link": "https://scsthub.in/",
        "ministry": "Ministry of MSME",
        "criteria": {
            "age_min": 18,
            "categories": ["SC", "ST"],
        },
        "documents": ["Caste Certificate", "Aadhaar Card", "Business Registration"],
    },
    {
        "id": "PMAGY",
        "name": "Pradhan Mantri Adarsh Gram Yojana",
        "description": "Village development scheme for villages with 50%+ SC population.",
        "official_link": "https://pmagy.gov.in/",
        "ministry": "Ministry of Social Justice & Empowerment",
        "criteria": {"category": "SC"},
        "documents": ["Caste Certificate", "Residence Proof", "Aadhaar"],
    },
    {
        "id": "POST_MATRIC",
        "name": "Post Matric Scholarship (SC/ST/OBC)",
        "description": "Scholarship for SC/ST/OBC students pursuing higher education.",
        "official_link": "https://scholarships.gov.in/",
        "ministry": "Ministry of Social Justice & Empowerment",
        "criteria": {
            "age_min": 16,
            "categories": ["SC", "ST", "OBC"],
        },
        "documents": ["Caste Certificate", "Income Certificate", "Previous Marksheet", "Aadhaar"],
    },
    # ========== EDUCATION SCHEMES ==========
    {
        "id": "SWAYAM",
        "name": "SWAYAM - Free Online Education",
        "description": "Free online courses from Class 9 to Post Graduation from IITs, IIMs, and top institutions.",
        "official_link": "https://swayam.gov.in/",
        "ministry": "Ministry of Education",
        "criteria": {"age_min": 14},
        "documents": ["Valid Email ID", "Mobile Number"],
    },
    {
        "id": "NPTEL",
        "name": "NPTEL – Online Education Initiative",
        "description": "Free online courses from IITs and IISc with certificates.",
        "official_link": "https://nptel.ac.in/",
        "ministry": "Ministry of Education",
        "criteria": {},
        "documents": ["Valid Email ID"],
    },
    {
        "id": "DIGITAL_INDIA",
        "name": "Digital India Internship",
        "description": "Internship opportunities for students in government digital initiatives.",
        "official_link": "https://digitalindia.gov.in/",
        "ministry": "Ministry of Electronics & IT",
        "criteria": {
            "age_min": 18,
            "occupations": ["student"],
        },
        "documents": ["College ID", "Resume", "Aadhaar"],
    },
    # ========== DIGITAL & CITIZEN SERVICES ==========
    {
        "id": "DIGILOCKER",
        "name": "DigiLocker",
        "description": "Cloud platform for digital storage and verification of government documents.",
        "official_link": "https://www.digilocker.gov.in/",
        "ministry": "Ministry of Electronics & IT",
        "criteria": {},
        "documents": ["Aadhaar Card", "Mobile Number"],
    },
    {
        "id": "UMANG",
        "name": "UMANG - Unified Mobile App",
        "description": "One app for 1,600+ government services – PF, pension, scholarships, and more.",
        "official_link": "https://www.umang.gov.in/",
        "ministry": "Ministry of Electronics & IT",
        "criteria": {},
        "documents": ["Aadhaar/Mobile for registration"],
    },
    # ========== STATE-SPECIFIC SCHEMES ==========
    {
        "id": "RYTHU_BANDHU",
        "name": "Rythu Bandhu (Telangana)",
        "description": "Investment support of ₹5,000/acre per season to farmers in Telangana.",
        "official_link": "https://rythubandhu.telangana.gov.in/",
        "ministry": "Government of Telangana",
        "criteria": {
            "farmer": True,
            "state": "Telangana",
        },
        "documents": ["Aadhaar", "Pattadar Passbook", "Bank Account"],
    },
    {
        "id": "KISAN_SAMMAN",
        "name": "Mukhyamantri Kisan Samman Nidhi (Bihar)",
        "description": "Additional ₹4,000 per year to farmers in Bihar over PM-KISAN.",
        "official_link": "https://dbtagriculture.bihar.gov.in/",
        "ministry": "Government of Bihar",
        "criteria": {
            "farmer": True,
            "state": "Bihar",
        },
        "documents": ["Aadhaar", "Bank Account", "Land Records"],
    },
    {
        "id": "GRUH_LAXMI",
        "name": "Gruh Laxmi Yojana (Gujarat)",
        "description": "One-time assistance of ₹1 lakh to newly married women from BPL families.",
        "official_link": "https://sje.gujarat.gov.in/",
        "ministry": "Government of Gujarat",
        "criteria": {
            "gender": "Female",
            "income_max": 120000,
            "age_min": 18,
            "state": "Gujarat",
        },
        "documents": ["Aadhaar", "Marriage Certificate", "Income Certificate", "Bank Account"],
    },
    {
        "id": "OLD_AGE_PENSION_UP",
        "name": "Mukhyamantri Vridhajan Pension Yojana (Uttar Pradesh)",
        "description": "Monthly pension of ₹500 for elderly (60+) in Uttar Pradesh.",
        "official_link": "https://sspy-up.gov.in/",
        "ministry": "Government of Uttar Pradesh",
        "criteria": {
            "age_min": 60,
            "income_max": 46000,
            "state": "Uttar Pradesh",
        },
        "documents": ["Aadhaar", "Age Proof", "Income Certificate", "Bank Account"],
    },
    {
        "id": "LADLI",
        "name": "Ladli Laxmi Yojana (Madhya Pradesh)",
        "description": "Financial assistance for girl child – bonds and cash at various milestones.",
        "official_link": "https://ladlilaxmi.mp.gov.in/",
        "ministry": "Government of Madhya Pradesh",
        "criteria": {
            "gender": "Female",
            "age_max": 1,
            "state": "Madhya Pradesh",
        },
        "documents": ["Birth Certificate", "Aadhaar", "Bank Account", "Residence Proof"],
    },
    {
        "id": "AMMA_SCHEME",
        "name": "Amma Scheme (Tamil Nadu)",
        "description": "Subsidized canteens and other welfare measures for economically weaker sections.",
        "official_link": "https://www.tn.gov.in/",
        "ministry": "Government of Tamil Nadu",
        "criteria": {"state": "Tamil Nadu"},
        "documents": ["Aadhaar", "Ration Card"],
    },
    {
        "id": "KARUNYA",
        "name": "Karunya Health Scheme (Kerala)",
        "description": "Health insurance for below-poverty-line families in Kerala.",
        "official_link": "https://karunya.kerala.gov.in/",
        "ministry": "Government of Kerala",
        "criteria": {
            "income_max": 300000,
            "state": "Kerala",
        },
        "documents": ["Aadhaar", "Ration Card", "Income Certificate", "Bank Account"],
    },
    {
        "id": "ANNAPURNA",
        "name": "Annapurna Scheme",
        "description": "10 kg free rice per month to indigent senior citizens (65+) not receiving NSAP.",
        "official_link": "https://nsap.nic.in/",
        "ministry": "Ministry of Rural Development",
        "criteria": {"age_min": 65},
        "documents": ["Age Proof", "Aadhaar", "Income Certificate"],
    },
    {
        "id": "VIKAS_BHARAT",
        "name": "Vikas Bharat Sankalp Yatra Benefits",
        "description": "Outreach to ensure eligible citizens get benefits of all central schemes.",
        "official_link": "https://sankalp.mygov.in/",
        "ministry": "Government of India",
        "criteria": {},
        "documents": ["Aadhaar", "Relevant scheme documents"],
    },
]
